install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.60.0/hugo_0.60.0_Windows-64bit.zip
  - sudo dpkg -1 hugo*.deb
  - hugo version
  before_script:
  - rm -rf public
  script:
  - hugo
  branches:
    only:
    - master  
